// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2d0SgBWCl2YNB-uHaLAvyI8mfrNuWDzA',
    appId: '1:839446191356:web:b1262b4cfd3502fc718b79',
    messagingSenderId: '839446191356',
    projectId: 'proj3k-6dfc6',
    authDomain: 'proj3k-6dfc6.firebaseapp.com',
    storageBucket: 'proj3k-6dfc6.appspot.com',
    measurementId: 'G-T8MMSYTB86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQevn-ckULMyX2vNvW0rygLo8IcU_Sxz8',
    appId: '1:839446191356:android:1ea513521712b22d718b79',
    messagingSenderId: '839446191356',
    projectId: 'proj3k-6dfc6',
    storageBucket: 'proj3k-6dfc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKuZby5PTpyXlaDIt2Osi8kAC7NlQX_n4',
    appId: '1:839446191356:ios:8bfc2f9bd683bfcf718b79',
    messagingSenderId: '839446191356',
    projectId: 'proj3k-6dfc6',
    storageBucket: 'proj3k-6dfc6.appspot.com',
    iosBundleId: 'com.example.proj3k',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKuZby5PTpyXlaDIt2Osi8kAC7NlQX_n4',
    appId: '1:839446191356:ios:0de2d7bc7d58130b718b79',
    messagingSenderId: '839446191356',
    projectId: 'proj3k-6dfc6',
    storageBucket: 'proj3k-6dfc6.appspot.com',
    iosBundleId: 'com.example.proj3k.RunnerTests',
  );
}
